"""The generated Lean corpus and its command-line write operation."""

from __future__ import annotations

from pathlib import Path

from .. import peano as _peano
from .. import presburger as _presburger
from .. import robinson as _robinson
from ..peano_proofs import mul_cancel_right_succ, mul_proof
from ..presburger_proofs import add_proof, left_identity_proof
from ..robinson_proofs import bridge_converse_positive, robinson_add_proof
from .models import model_for
from .proof import _Export

# ---------------------------------------------------------------------------
# The corpus: one self-contained Lean file
# ---------------------------------------------------------------------------

CORPUS_PATH = Path(__file__).resolve().parents[2] / "lean_export" / "ColdStart.lean"

_HEADER = """/-
  ColdStart.lean

  Generated by `uv run python -m cold_start.lean` -- do not edit by hand.

  Each theorem below is a proof term from the `cold_start` checker, re-rendered
  for Lean 4. The point is the De Bruijn criterion: our checker re-derives a
  proof instead of trusting it, and this file hands the same derivations to a
  completely independent kernel. If Lean accepts this file, two unrelated
  implementations agree.

  Nothing here is asserted. There are no `axiom` declarations, no placeholder
  proofs and no tactics: each theorem is CONDITIONAL, taking the operations and
  the axioms of its theory (and, where the proof uses induction, the induction
  principle) as hypotheses over an abstract carrier `M`. The epilogue then
  instantiates each theorem whose exact theory has a registered semantic model,
  discharging every hypothesis with a Lean proof term. The current registry
  contains the Presburger and Peano models at `Nat`.

  Lean core only: this file needs no `import`, no Std and no Mathlib.
-/

-- Every theorem takes its theory's WHOLE axiom set as hypotheses, whether or not
-- a given proof cites all of them, so that the axioms are visible in the
-- statement and the epilogue can discharge them by name. Lean would otherwise
-- report each uncited one as an unused binder.
set_option linter.unusedVariables false
"""

_EPILOGUE_HEADER = """/-
  The epilogue: registered semantic models discharge every hypothesis, so the
  corresponding conditional theorems become unconditional facts.

  Robinson's theory is deliberately absent here. Its axioms describe the
  POSITIVE integers (A1 says `succ a ≠ 1`, which is false at `a := 0`), so `Nat`
  is not a model of it and the theorem above stays conditional -- as it should.
-/
"""


def corpus_entries() -> list:
    """The proofs the generated file carries: `(name, proof, theory)`.

    Cash-out is decided only by the exact semantic model registry; entries do
    not carry an ad hoc boolean permission.
    """
    return [
        ("coldstart_left_identity", left_identity_proof(), _presburger.PRESBURGER),
        ("coldstart_add_two_three", add_proof(2, 3), _presburger.PRESBURGER),
        ("coldstart_mul_two_three", mul_proof(2, 3), _peano.PEANO),
        (
            "coldstart_mul_cancel_right_positive",
            mul_cancel_right_succ(),
            _peano.PEANO,
        ),
        (
            "coldstart_robinson_bridge_converse_positive",
            bridge_converse_positive(),
            _peano.PEANO,
        ),
        (
            "coldstart_robinson_add_two_three",
            robinson_add_proof(2, 3),
            _robinson.ROBINSON_PEANO,
        ),
    ]


CORPUS_NAMES = tuple(name for name, _pf, _theory in corpus_entries())


def export_corpus() -> str:
    """The whole `ColdStart.lean`: header, one conditional theorem per corpus
    proof, then the semantic-model epilogue."""
    parts = [_HEADER]
    epilogue = [_EPILOGUE_HEADER]
    for name, pf, theory in corpus_entries():
        export = _Export(pf, theory)
        parts.append(export.theorem(name))
        model = model_for(theory)
        if model is not None:
            epilogue.append(export.model_example(name, model))
    return "\n".join([*parts, *epilogue])


def write_corpus(path: Path | str | None = None) -> Path:
    """Write `export_corpus()` to `path` (default `lean_export/ColdStart.lean`),
    with LF endings so the checked-in file is stable across platforms."""
    target = Path(path) if path is not None else CORPUS_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(export_corpus())
    return target


__all__ = [
    "CORPUS_NAMES",
    "CORPUS_PATH",
    "corpus_entries",
    "export_corpus",
    "write_corpus",
]
