"""The generated Lean corpus and its command-line write operation."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .. import algebra as _algebra
from .. import peano as _peano
from .. import presburger as _presburger
from .. import robinson as _robinson
from ..algebra_proofs import ring_add_cancel_right
from ..bridges import ADD_ONE_F, ADD_SUCC_F, PRESBURGER_ONE
from ..cubicring import CUBE, CUBIC_RING, GEN_TH, TWO
from ..diffring2 import DIFF_RING_2
from ..diffring2_proofs import derivation_zero_proofs
from ..divisibility_bridges import (
    BARE_MULTIPLICATION,
    DIVIDES_REFL_ATOM,
    DIVISIBILITY_CORE,
    PURE_SUCCESSOR_DIVISIBILITY,
    divisibility_into_peano,
)
from ..groupring2 import GROUP_RING_P2
from ..integers import integers_interpretation
from ..kaplansky_proofs import cancellation_rules
from ..order import le_refl
from ..parity import parity
from ..peano_proofs import mul_cancel_right_succ, mul_proof
from ..presburger_proofs import add_proof, left_identity_proof
from ..proof import Axiom, Cong, Pf, Refl, Trans
from ..robinson_divisibility_proofs import coprime_one_left
from ..robinson_proofs import bridge_converse_positive, robinson_add_proof
from ..skolem import skolem_interpretation
from ..squaring import SQUARE_ARITHMETIC
from ..squaring_bridges import BARE_MULTIPLICATION_FROM_SQUARE
from ..squaring_proofs import square_product_total, square_product_unique
from ..syntax import Var
from ..tactics import axiom_rule
from ..theory import Theory
from ..vocabulary import ONE, ZERO, mul
from .models import model_for
from .proof import LeanProofExport

# ---------------------------------------------------------------------------
# The corpus: one self-contained Lean file
# ---------------------------------------------------------------------------

CORPUS_PATH = Path(__file__).resolve().parents[2] / "lean_export" / "ColdStart.lean"

_HEADER = """/-
  ColdStart.lean

  Generated by `uv run python -m cold_start.lean` -- do not edit by hand.

  Each theorem below is a proof term from the `cold_start` checker, re-rendered
  for Lean 4. The point is the De Bruijn criterion: our checker re-derives a
  proof instead of trusting it, and this file hands the same derivations to a
  completely independent kernel. If Lean accepts this file, two unrelated
  implementations agree.

  Nothing here is asserted. There are no `axiom` declarations, no placeholder
  proofs and no tactics: each theorem is CONDITIONAL, taking the operations and
  the axioms of its theory (and, where the proof uses induction, the induction
  principle) as hypotheses over an abstract carrier `M`. The epilogue then
  instantiates each theorem whose exact theory has a registered semantic model,
  discharging every hypothesis with a Lean proof term. The current registry
  contains the Presburger, Peano, and addition-plus-square models at `Nat`.

  Lean core only: this file needs no `import`, no Std and no Mathlib.
-/

-- Every theorem takes its theory's WHOLE axiom set as hypotheses, whether or not
-- a given proof cites all of them, so that the axioms are visible in the
-- statement and the epilogue can discharge them by name. Lean would otherwise
-- report each uncited one as an unused binder.
set_option linter.unusedVariables false
"""

_EPILOGUE_HEADER = """/-
  The epilogue: registered semantic models discharge every hypothesis, so the
  corresponding conditional theorems become unconditional facts.

  Robinson's theory is deliberately absent here. Its axioms describe the
  POSITIVE integers (A1 says `succ a ≠ 1`, which is false at `a := 0`), so `Nat`
  is not a model of it and the theorem above stays conditional -- as it should.
-/
"""


@dataclass(frozen=True, slots=True)
class CorpusEntry:
    """One independently checked theorem and its semantic coverage roles."""

    name: str
    proof: Pf
    theory: Theory
    features: frozenset[str] = frozenset()


OFFICIAL_THEORIES: tuple[tuple[str, Theory], ...] = (
    # Every theory the corpus is expected to carry a REAL theorem for. Coverage
    # is measured against this roster: a theory listed here with no theorem of
    # its own is reported missing, by name. Nothing is padded to close the gap.
    ("presburger-one", PRESBURGER_ONE),
    ("presburger", _presburger.PRESBURGER),
    ("peano", _peano.PEANO),
    ("robinson", _robinson.ROBINSON_PEANO),
    ("semigroup", _algebra.SEMIGROUP),
    ("monoid", _algebra.MONOID),
    ("commutative-monoid", _algebra.COMM_MONOID),
    ("ring", _algebra.RING),
    ("commutative-ring", _algebra.COMM_RING),
    ("abelian-group", _algebra.AB_GROUP),
    ("divisibility-core", DIVISIBILITY_CORE),
    ("addition-and-square", SQUARE_ARITHMETIC),
    ("group-ring-p2", GROUP_RING_P2),
    ("cubic-ring", CUBIC_RING),
    ("differential-ring", DIFF_RING_2),
)

EXCLUDED_THEORIES: tuple[tuple[str, Theory, str], ...] = (
    # Theories the export deliberately carries no theorem for, each with the
    # reason it cannot have one. An exclusion is stated here and reported; it is
    # never hidden behind a filler theorem.
    (
        "monoid-action",
        _algebra.MONOID_ACTION,
        "many-sorted (a monoid acting on a set): Lean's one-carrier fragment "
        "cannot state it without changing its semantics",
    ),
    (
        "successor-divisibility",
        PURE_SUCCESSOR_DIVISIBILITY,
        "an axiom-free interpretation SOURCE signature: nothing but tautologies "
        "is derivable in it, so no honest theorem exists",
    ),
    (
        "bare-multiplication",
        BARE_MULTIPLICATION,
        "an axiom-free interpretation SOURCE signature: nothing but tautologies "
        "is derivable in it, so no honest theorem exists",
    ),
    (
        "multiplication-from-square",
        BARE_MULTIPLICATION_FROM_SQUARE,
        "an axiom-free interpretation SOURCE signature: nothing but tautologies "
        "is derivable in it, so no honest theorem exists",
    ),
)


# ---------------------------------------------------------------------------
# Small theorems for the theories that have no proof module of their own
# ---------------------------------------------------------------------------
# Each is written out here rather than generated: a theorem stands for its
# theory only if it actually USES that theory's axioms, and the shortest honest
# way to say so is to derive one real fact per theory by hand.

_x, _y, _z, _w = Var("x"), Var("y"), Var("z"), Var("w")
_a = Var("a")


def semigroup_reassociation() -> Pf:
    """((w*x)*y)*z = w*(x*(y*z)): the associativity axiom used twice."""
    assoc = axiom_rule(_algebra.ASSOC)
    return Trans(
        assoc.instance({"x": mul(_w, _x), "y": _y, "z": _z}),
        assoc.instance({"x": _w, "y": _x, "z": mul(_y, _z)}),
    )


def monoid_unit_idempotent() -> Pf:
    """e*e = e: the left identity read at the unit itself."""
    return axiom_rule(_algebra.LEFT_ID).instance({"x": _algebra.E})


def commutative_monoid_right_identity() -> Pf:
    """x*e = x, derived from commutativity and the LEFT identity -- the right
    identity axiom is redundant once `*` commutes, and this proof shows it."""
    return Trans(
        axiom_rule(_algebra.COMM).instance({"x": _x, "y": _algebra.E}),
        axiom_rule(_algebra.LEFT_ID).instance({"x": _x}),
    )


def abelian_group_left_identity() -> Pf:
    """0+x = x, from commutativity of `+` and the right-sided axiom."""
    return Trans(
        axiom_rule(_algebra.ADD_COMM).instance({"x": ZERO, "y": _x}),
        axiom_rule(_algebra.ADD_ZERO).instance({"x": _x}),
    )


def ring_mul_add_one() -> Pf:
    """x*(y+1) = x*y + x: distributivity followed by the right unit, under the
    congruence rule -- the shape every polynomial expansion is made of."""
    return Trans(
        axiom_rule(_algebra.DIST_LEFT).instance({"x": _x, "y": _y, "z": ONE}),
        Cong("+", (Refl(mul(_x, _y)), axiom_rule(_algebra.MUL_RIGHT_ID).instance({"x": _x}))),
    )


def presburger_one_add_two() -> Pf:
    """a + S 1 = S (S a) in the 1-based Presburger theory, which has no zero."""
    return Trans(
        axiom_rule(ADD_SUCC_F).instance({"a": _a, "b": ONE}),
        Cong("S", (axiom_rule(ADD_ONE_F).instance({"a": _a}),)),
    )


def cubic_ring_theta_fourth() -> Pf:
    """th*(th*(th*th)) = 2*th in Z[th | th^3 = 2]: the cube relation under a
    congruence, then commutativity. The full norm factorization lives in
    `cubicring_proofs`; it is a 2.4 MB export, so the corpus carries this one."""
    return Trans(
        Cong("*", (Refl(GEN_TH), Axiom(CUBE))),
        axiom_rule(_algebra.COMM).instance({"x": GEN_TH, "y": TWO}),
    )


def corpus_entries() -> list[CorpusEntry]:
    """The proofs carried by the generated corpus.

    Cash-out is decided only by the exact semantic model registry; entries do
    not carry an ad hoc boolean permission. Feature labels describe why a proof
    is present; they do not affect checking or Lean rendering.
    """
    ordinary = divisibility_into_peano()
    quotient = integers_interpretation()
    # The quotient interpretation's first obligation is discharged by plain
    # reflexivity, which is a theorem of no theory at all; the first RESPECT
    # obligation -- that the constant respects the equivalence -- is the
    # smallest payment that actually uses the target's axioms.
    quotient_payment = next(
        proof for key, proof in quotient.payments if key.kind == "respect"
    )
    return [
        CorpusEntry(
            "coldstart_left_identity",
            left_identity_proof(),
            _presburger.PRESBURGER,
            frozenset({"proof-family:presburger"}),
        ),
        CorpusEntry(
            "coldstart_add_two_three",
            add_proof(2, 3),
            _presburger.PRESBURGER,
            frozenset({"proof-family:presburger"}),
        ),
        CorpusEntry(
            "coldstart_mul_two_three",
            mul_proof(2, 3),
            _peano.PEANO,
            frozenset({"proof-family:peano"}),
        ),
        CorpusEntry(
            "coldstart_mul_cancel_right_positive",
            mul_cancel_right_succ(),
            _peano.PEANO,
            frozenset({"proof-family:peano"}),
        ),
        CorpusEntry(
            "coldstart_robinson_bridge_converse_positive",
            bridge_converse_positive(),
            _peano.PEANO,
            frozenset({"proof-family:robinson"}),
        ),
        CorpusEntry(
            "coldstart_robinson_add_two_three",
            robinson_add_proof(2, 3),
            _robinson.ROBINSON_PEANO,
            frozenset({"proof-family:robinson"}),
        ),
        CorpusEntry(
            "coldstart_square_product_total",
            square_product_total(),
            SQUARE_ARITHMETIC,
            frozenset({"proof-family:squaring"}),
        ),
        CorpusEntry(
            "coldstart_square_product_unique",
            square_product_unique(),
            SQUARE_ARITHMETIC,
            frozenset({"proof-family:squaring"}),
        ),
        CorpusEntry(
            "coldstart_relation_reflexive",
            Axiom(DIVIDES_REFL_ATOM),
            DIVISIBILITY_CORE,
            # "relations" is not asserted here: coverage derives it from this
            # entry's own `Rel` nodes.
            frozenset({"proof-family:divisibility"}),
        ),
        CorpusEntry(
            "coldstart_ordinary_interpretation_payment",
            ordinary.payments[0][1],
            ordinary.target,
            frozenset({"ordinary-interpretation", "proof-family:divisibility"}),
        ),
        CorpusEntry(
            "coldstart_quotient_interpretation_payment",
            quotient_payment,
            quotient.target,
            frozenset({"quotient-interpretation", "proof-family:integer-pairs"}),
        ),
        CorpusEntry(
            "coldstart_order_reflexive",
            le_refl(),
            _presburger.PRESBURGER,
            frozenset({"proof-family:order"}),
        ),
        CorpusEntry(
            "coldstart_parity",
            parity(),
            _peano.PEANO,
            frozenset({"proof-family:parity"}),
        ),
        CorpusEntry(
            "coldstart_robinson_divisibility_unit",
            coprime_one_left(),
            _peano.PEANO,
            frozenset({"proof-family:robinson-divisibility"}),
        ),
        CorpusEntry(
            "coldstart_skolem_payment",
            skolem_interpretation().payments[0][1],
            _peano.PEANO,
            frozenset({"proof-family:skolem", "ordinary-interpretation"}),
        ),
        CorpusEntry(
            "coldstart_presburger_one_add_two",
            presburger_one_add_two(),
            PRESBURGER_ONE,
            frozenset({"proof-family:presburger"}),
        ),
        CorpusEntry(
            "coldstart_semigroup_reassociation",
            semigroup_reassociation(),
            _algebra.SEMIGROUP,
            frozenset({"proof-family:algebra"}),
        ),
        CorpusEntry(
            "coldstart_monoid_unit_idempotent",
            monoid_unit_idempotent(),
            _algebra.MONOID,
            frozenset({"proof-family:algebra"}),
        ),
        CorpusEntry(
            "coldstart_commutative_monoid_right_identity",
            commutative_monoid_right_identity(),
            _algebra.COMM_MONOID,
            frozenset({"proof-family:algebra"}),
        ),
        CorpusEntry(
            "coldstart_ring_mul_add_one",
            ring_mul_add_one(),
            _algebra.RING,
            frozenset({"proof-family:algebra"}),
        ),
        CorpusEntry(
            "coldstart_commutative_ring_add_cancel_right",
            ring_add_cancel_right(),
            _algebra.COMM_RING,
            frozenset({"proof-family:algebra"}),
        ),
        CorpusEntry(
            "coldstart_abelian_group_left_identity",
            abelian_group_left_identity(),
            _algebra.AB_GROUP,
            frozenset({"proof-family:algebra"}),
        ),
        CorpusEntry(
            "coldstart_group_ring_inverse_cancels",
            cancellation_rules()[0].proof,
            GROUP_RING_P2,
            frozenset({"proof-family:group-ring"}),
        ),
        CorpusEntry(
            "coldstart_cubic_ring_theta_fourth",
            cubic_ring_theta_fourth(),
            CUBIC_RING,
            frozenset({"proof-family:cubic-ring"}),
        ),
        CorpusEntry(
            "coldstart_differential_ring_derivation_of_zero",
            derivation_zero_proofs()[0],
            DIFF_RING_2,
            frozenset({"proof-family:differential-ring"}),
        ),
    ]


CORPUS_NAMES = tuple(entry.name for entry in corpus_entries())


def export_corpus() -> str:
    """The whole `ColdStart.lean`: header, one conditional theorem per corpus
    proof, then the semantic-model epilogue."""
    parts = [_HEADER]
    model_examples: list[str] = []
    for entry in corpus_entries():
        export = LeanProofExport(entry.proof, entry.theory)
        parts.append(export.theorem(entry.name))
        model = model_for(entry.theory)
        if model is not None:
            model_examples.append(export.model_example(entry.name, model))
    return "\n".join([*parts, _EPILOGUE_HEADER, *model_examples])


def write_corpus(path: Path | str | None = None) -> Path:
    """Write `export_corpus()` to `path` (default `lean_export/ColdStart.lean`),
    with LF endings so the checked-in file is stable across platforms."""
    target = Path(path) if path is not None else CORPUS_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(export_corpus())
    return target


__all__ = [
    "CORPUS_NAMES",
    "CORPUS_PATH",
    "CorpusEntry",
    "EXCLUDED_THEORIES",
    "OFFICIAL_THEORIES",
    "corpus_entries",
    "export_corpus",
    "write_corpus",
]
