from collections.abc import Callable, Iterator, Mapping
from typing import Final

MAGIC: Final[bytes]
__version__: str

class HamblinError(ValueError): ...

def encode_to(node: object, write: Callable[[bytes], object]) -> None: ...
def encode(node: object) -> bytes: ...
def decode_from(read: Callable[[int], bytes], registry: Mapping[str, type[object]]) -> object: ...
def decode(data: bytes, registry: Mapping[str, type[object]]) -> object: ...
def iter_records(data: bytes) -> Iterator[tuple[object, ...]]: ...
