/-
  ColdStart.lean

  Generated by `uv run python -m cold_start.lean` -- do not edit by hand.

  Each theorem below is a proof term from the `cold_start` checker, re-rendered
  for Lean 4. The point is the De Bruijn criterion: our checker re-derives a
  proof instead of trusting it, and this file hands the same derivations to a
  completely independent kernel. If Lean accepts this file, two unrelated
  implementations agree.

  Nothing here is asserted. There are no `axiom` declarations, no placeholder
  proofs and no tactics: each theorem is CONDITIONAL, taking the operations and
  the axioms of its theory (and, where the proof uses induction, the induction
  principle) as hypotheses over an abstract carrier `M`. The epilogue then
  instantiates them at Lean's own `Nat`, discharging every hypothesis with a
  core lemma, which turns them into unconditional facts about the naturals.

  Lean core only: this file needs no `import`, no Std and no Mathlib.
-/

-- Every theorem takes its theory's WHOLE axiom set as hypotheses, whether or not
-- a given proof cites all of them, so that the axioms are visible in the
-- statement and the epilogue can discharge them by name. Lean would otherwise
-- report each uncited one as an unused binder.
set_option linter.unusedVariables false

theorem coldstart_left_identity {M : Type} (zero : M) (succ : M → M) (add : M → M → M)
    (ax_add_succ : ∀ x : M, ∀ y : M, add x (succ y) = succ (add x y))
    (ax_add_zero : ∀ x : M, add x zero = x)
    (ax_succ_inj : ∀ x : M, ∀ y : M, succ x = succ y → x = y)
    (ax_succ_ne_zero : ∀ x : M, succ x = zero → False)
    (ind : ∀ P : M → Prop, P zero → (∀ n : M, P n → P (succ n)) → ∀ n : M, P n)
    : ∀ n : M, add zero n = n :=
  fun n : M => (ind (fun n_1 : M => add zero n_1 = n_1) (ax_add_zero zero) (fun n_2 : M => (fun h : add zero n_2 = n_2 => (Eq.trans (ax_add_succ zero n_2) (congrArg succ h)))) n)

theorem coldstart_add_two_three {M : Type} (zero : M) (succ : M → M) (add : M → M → M)
    (ax_add_succ : ∀ x : M, ∀ y : M, add x (succ y) = succ (add x y))
    (ax_add_zero : ∀ x : M, add x zero = x)
    (ax_succ_inj : ∀ x : M, ∀ y : M, succ x = succ y → x = y)
    (ax_succ_ne_zero : ∀ x : M, succ x = zero → False)
    : add (succ (succ zero)) (succ (succ (succ zero))) = succ (succ (succ (succ (succ zero)))) :=
  (Eq.trans (ax_add_succ (succ (succ zero)) (succ (succ zero))) (congrArg succ (Eq.trans (ax_add_succ (succ (succ zero)) (succ zero)) (congrArg succ (Eq.trans (ax_add_succ (succ (succ zero)) zero) (congrArg succ (ax_add_zero (succ (succ zero)))))))))

theorem coldstart_mul_two_three {M : Type} (zero : M) (succ : M → M) (add : M → M → M)
    (mul : M → M → M)
    (ax_add_succ : ∀ x : M, ∀ y : M, add x (succ y) = succ (add x y))
    (ax_add_zero : ∀ x : M, add x zero = x)
    (ax_mul_succ : ∀ x : M, ∀ y : M, mul x (succ y) = add (mul x y) x)
    (ax_mul_zero : ∀ x : M, mul x zero = zero)
    (ax_succ_inj : ∀ x : M, ∀ y : M, succ x = succ y → x = y)
    (ax_succ_ne_zero : ∀ x : M, succ x = zero → False)
    : mul (succ (succ zero)) (succ (succ (succ zero))) = succ (succ (succ (succ (succ (succ zero))))) :=
  (Eq.trans (ax_mul_succ (succ (succ zero)) (succ (succ zero))) (Eq.trans (congr (congrArg add (Eq.trans (ax_mul_succ (succ (succ zero)) (succ zero)) (Eq.trans (congr (congrArg add (Eq.trans (ax_mul_succ (succ (succ zero)) zero) (Eq.trans (congr (congrArg add (ax_mul_zero (succ (succ zero)))) (Eq.refl (succ (succ zero)))) (Eq.trans (ax_add_succ zero (succ zero)) (congrArg succ (Eq.trans (ax_add_succ zero zero) (congrArg succ (ax_add_zero zero)))))))) (Eq.refl (succ (succ zero)))) (Eq.trans (ax_add_succ (succ (succ zero)) (succ zero)) (congrArg succ (Eq.trans (ax_add_succ (succ (succ zero)) zero) (congrArg succ (ax_add_zero (succ (succ zero)))))))))) (Eq.refl (succ (succ zero)))) (Eq.trans (ax_add_succ (succ (succ (succ (succ zero)))) (succ zero)) (congrArg succ (Eq.trans (ax_add_succ (succ (succ (succ (succ zero)))) zero) (congrArg succ (ax_add_zero (succ (succ (succ (succ zero)))))))))))

theorem coldstart_robinson_add_two_three {M : Type} (zero : M) (succ : M → M) (mul : M → M → M)
    (ax_add_one : ∀ a : M, mul (succ (mul a (succ a))) (succ (mul (succ zero) (succ a))) = succ (mul (mul (succ a) (succ a)) (succ (mul a (succ zero)))))
    (ax_add_succ : ∀ a : M, ∀ b : M, ∀ c : M, mul (succ (mul a c)) (succ (mul b c)) = succ (mul (mul c c) (succ (mul a b))) → mul (succ (mul a (succ c))) (succ (mul (succ b) (succ c))) = succ (mul (mul (succ c) (succ c)) (succ (mul a (succ b)))))
    (ax_mul_one : ∀ a : M, mul a (succ zero) = a)
    (ax_mul_succ : ∀ a : M, ∀ b : M, mul (succ (mul (mul a b) (mul a (succ b)))) (succ (mul a (mul a (succ b)))) = succ (mul (mul (mul a (succ b)) (mul a (succ b))) (succ (mul (mul a b) a))))
    (ax_succ_inj : ∀ a : M, ∀ b : M, succ a = succ b → a = b)
    (ax_succ_ne_one : ∀ a : M, succ a = succ zero → False)
    : mul (succ (mul (succ (succ zero)) (succ (succ (succ (succ (succ zero))))))) (succ (mul (succ (succ (succ zero))) (succ (succ (succ (succ (succ zero))))))) = succ (mul (mul (succ (succ (succ (succ (succ zero))))) (succ (succ (succ (succ (succ zero)))))) (succ (mul (succ (succ zero)) (succ (succ (succ zero)))))) :=
  ((ax_add_succ (succ (succ zero)) (succ (succ zero)) (succ (succ (succ (succ zero))))) ((ax_add_succ (succ (succ zero)) (succ zero) (succ (succ (succ zero)))) (ax_add_one (succ (succ zero)))))

/-
  The epilogue: `M := Nat`, with every hypothesis discharged, so the conditional
  theorems above become unconditional facts about Lean's own naturals.

  Robinson's theory is deliberately absent here. Its axioms describe the
  POSITIVE integers (A1 says `succ a ≠ 1`, which is false at `a := 0`), so `Nat`
  is not a model of it and the theorem above stays conditional -- as it should.
-/

example : ∀ n : Nat, Nat.add Nat.zero n = n :=
  coldstart_left_identity (M := Nat)
    (zero := Nat.zero)
    (succ := Nat.succ)
    (add := Nat.add)
    (ax_add_succ := fun x y => rfl)
    (ax_add_zero := fun x => rfl)
    (ax_succ_inj := fun x y h => Nat.noConfusion h (fun h' => h'))
    (ax_succ_ne_zero := fun x h => Nat.noConfusion h)
    (ind := fun P h0 hs n => Nat.rec (motive := P) h0 hs n)

example : Nat.add (Nat.succ (Nat.succ Nat.zero)) (Nat.succ (Nat.succ (Nat.succ Nat.zero))) = Nat.succ (Nat.succ (Nat.succ (Nat.succ (Nat.succ Nat.zero)))) :=
  coldstart_add_two_three (M := Nat)
    (zero := Nat.zero)
    (succ := Nat.succ)
    (add := Nat.add)
    (ax_add_succ := fun x y => rfl)
    (ax_add_zero := fun x => rfl)
    (ax_succ_inj := fun x y h => Nat.noConfusion h (fun h' => h'))
    (ax_succ_ne_zero := fun x h => Nat.noConfusion h)

example : Nat.mul (Nat.succ (Nat.succ Nat.zero)) (Nat.succ (Nat.succ (Nat.succ Nat.zero))) = Nat.succ (Nat.succ (Nat.succ (Nat.succ (Nat.succ (Nat.succ Nat.zero))))) :=
  coldstart_mul_two_three (M := Nat)
    (zero := Nat.zero)
    (succ := Nat.succ)
    (add := Nat.add)
    (mul := Nat.mul)
    (ax_add_succ := fun x y => rfl)
    (ax_add_zero := fun x => rfl)
    (ax_mul_succ := fun x y => rfl)
    (ax_mul_zero := fun x => rfl)
    (ax_succ_inj := fun x y h => Nat.noConfusion h (fun h' => h'))
    (ax_succ_ne_zero := fun x h => Nat.noConfusion h)
